"""GitHub 관리 유틸리티"""
import os
import subprocess
from pathlib import Path
from typing import Optional, Dict
from src.utils.logger import setup_logger

logger = setup_logger('github_manager')


class GitHubManager:
    """GitHub 리포지토리 관리 클래스"""

    def __init__(self, github_token: Optional[str] = None, github_username: str = "cham7766-dotcom"):
        """
        GitHub Manager 초기화

        Args:
            github_token: GitHub Personal Access Token (선택)
            github_username: GitHub 사용자명
        """
        self.github_token = github_token
        self.github_username = github_username
        self.base_path = Path.home() / "Desktop"

    def create_and_push_project(
        self,
        project_name: str,
        code: str,
        language: str,
        commit_message: str = "Generated code by Gemini AI"
    ) -> Dict[str, str]:
        """
        프로젝트를 생성하고 GitHub에 푸시

        Args:
            project_name: 프로젝트 이름
            code: 생성된 코드
            language: 프로그래밍 언어
            commit_message: 커밋 메시지

        Returns:
            {
                "success": True/False,
                "github_url": "GitHub 리포지토리 URL",
                "error": "오류 메시지 (실패 시)"
            }
        """
        try:
            # 프로젝트 디렉토리 생성
            project_path = self.base_path / project_name
            project_path.mkdir(parents=True, exist_ok=True)

            # 파일 확장자 결정
            file_extension = self._get_file_extension(language)
            main_file = project_path / f"main.{file_extension}"

            # 코드 파일 작성
            with open(main_file, 'w', encoding='utf-8') as f:
                f.write(code)

            # README.md 생성
            readme_path = project_path / "README.md"
            with open(readme_path, 'w', encoding='utf-8') as f:
                f.write(f"# {project_name}\n\n")
                f.write(f"Generated by Gemini AI\n\n")
                f.write(f"Language: {language}\n")

            # Git 초기화
            self._run_git_command(project_path, "git init")
            self._run_git_command(project_path, "git add .")
            self._run_git_command(project_path, f'git commit -m "{commit_message}"')

            # GitHub 리포지토리 URL
            repo_url = f"https://github.com/{self.github_username}/{project_name}.git"

            # Remote 추가 및 푸시
            try:
                self._run_git_command(project_path, f"git remote add origin {repo_url}")
            except:
                # Remote가 이미 존재하는 경우
                pass

            self._run_git_command(project_path, "git branch -M main")

            # Push (토큰이 있으면 사용)
            if self.github_token:
                auth_url = f"https://{self.github_token}@github.com/{self.github_username}/{project_name}.git"
                self._run_git_command(project_path, f"git remote set-url origin {auth_url}")

            self._run_git_command(project_path, "git push -u origin main")

            logger.info(f"Successfully pushed {project_name} to GitHub")

            return {
                "success": True,
                "github_url": f"https://github.com/{self.github_username}/{project_name}",
                "local_path": str(project_path)
            }

        except Exception as e:
            logger.error(f"Failed to push to GitHub: {e}")
            return {
                "success": False,
                "error": str(e)
            }

    def _run_git_command(self, cwd: Path, command: str):
        """Git 명령어 실행"""
        try:
            result = subprocess.run(
                command,
                cwd=cwd,
                shell=True,
                capture_output=True,
                text=True,
                encoding='utf-8'
            )

            if result.returncode != 0:
                logger.warning(f"Git command warning: {result.stderr}")

            return result.stdout
        except Exception as e:
            logger.error(f"Git command failed: {e}")
            raise

    def _get_file_extension(self, language: str) -> str:
        """언어별 파일 확장자 반환"""
        extensions = {
            'python': 'py',
            'javascript': 'js',
            'java': 'java',
            'cpp': 'cpp',
            'c': 'c',
            'go': 'go',
            'rust': 'rs',
            'ruby': 'rb',
            'php': 'php',
            'swift': 'swift',
            'kotlin': 'kt',
            'typescript': 'ts',
            'html': 'html',
            'css': 'css'
        }
        return extensions.get(language.lower(), 'txt')
